"""lol

Revision ID: 4a803b69dcac
Revises: d70fe469229b
Create Date: 2022-08-13 10:11:34.889163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a803b69dcac'
down_revision = 'd70fe469229b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('event', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('events_subscribed', sa.Integer(), nullable=True))
    op.alter_column('user', 'permissions_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user', 'event', ['events_subscribed'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'permissions_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'events_subscribed')
    op.drop_column('event', 'sort_order')
    op.drop_column('event', 'categories')
    # ### end Alembic commands ###
