"""lmaolol

Revision ID: e887d31df71e
Revises: 2bb2dae82b87
Create Date: 2022-08-13 21:36:50.184715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e887d31df71e'
down_revision = '2bb2dae82b87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
