"""lmaolol

Revision ID: ee470714da99
Revises: c589e3903a73
Create Date: 2022-08-13 21:30:07.562672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee470714da99'
down_revision = 'c589e3903a73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_updated_by_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('permissions_updated_by_fkey', 'permissions', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###
